import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import ProviderSession from "@/context/Provider/session";
import ProviderRedux from "@/context/Provider/redux";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Delivery",
  description: "Generated by Zutto",
  applicationName: "Zutto Food",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ProviderSession>
          <ProviderRedux>
            <Navbar />
            <ToastContainer />
            {children}
            <Footer />
          </ProviderRedux>
        </ProviderSession>
      </body>
    </html>
  );
}
